"""init

Revision ID: a171f6c6e0a2
Revises: 
Create Date: 2024-02-18 22:36:40.106874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a171f6c6e0a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('HashedPassword', sa.String(length=1024), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsVerified', sa.Boolean(), nullable=False),
    sa.Column('VerifiedAt', sa.DateTime(), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_User_Email'), 'User', ['Email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
